### ISSUE TITLE
Ops Internal Budget Discussion on Cloud Test Environment

### ISSUE THREAD

**Issue by MeghanLuecke** [18F/dos-ops-center#119]
As an Ops project lead, I want to understand what options the Department has for reallocating funding from the existing contract toward an internal Department office to set up a test environment (if we decide to pursue this route).

AC: 

- [x] Meet with S Bureau EX office to discuss options
- [x] Update the team

**Comment by karareinsel** [comment]
Email from Meghan (2/13/2019) with updated information - 
We had a good meeting with our budget (“EX”) folks here in the S Bureau today and learned that there are, indeed, options for reallocating the $25,000 set aside in our original agreement for funding a cloud test environment. It’s a bit convoluted, and would involve 18F routing that money back into State through an agreement with IRM, but at least we now know it will be possible! This would allow us to apply the existing funding toward State’s nascent internal capability to create a cloud test environment rather than going outside (if that’s what the team ultimately recommends). We can provide more details but wanted to just give folks the bottom-line readout.
