### ISSUE TITLE
Finding out what ATO controls are supported

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#134]
As an 18F researcher, I want to discover what cloud controls are provided out of the box that should help ops systems get to production in the cloud, so they can get to the cloud faster and easier.

AC:
* [x]  Find out what the ATO controls are that are supported — answer: still TBD.
* [ ] ~Determine if the IRM's cloud platform is the same as the Cloud PMO~

Support:
@karareinsel 
@beebouttw

**Comment by beebouttw** [comment]
Updated #92 with response from IRM/IA/ITSC/AA

**Comment by brandocalrissian** [comment]
Based on [@beebouttw 's latest update](https://github.com/18f/dos-ops-center/issues/92#issuecomment-467024567), it looks like IA is still working on this list. We appear to be pioneers in this land.

**Comment by brandocalrissian** [comment]
@beebouttw Could you please ask Gene Cho if the IRM's cloud platform is the same as the Cloud PMO? We believe they are the same but would be nice to get a confirmation from someone who plays a role in the "getting to production" path.

Thank you!

**Comment by beebouttw** [comment]
Just reached out to Gene, since frankly his response makes no sense to me.  There appear to multiple overlapping layers of security requirements, and I'm not sure what relationship one bears to the next, so I've asked if I can speak to him by phone for a few minutes later today.  I might only be dispelling my personal misunderstandings, but I'll report back.

**Comment by brandocalrissian** [comment]
Thank you!

**Comment by brandocalrissian** [comment]
Splitting #161 from this as we added it after sprint planning and it's not specifically what this ticket was about.
