### ISSUE TITLE
Figure out who knows how to extract things from Email

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#135]
As an 18F researcher, I want to figure out WHO to talk to about extracting data from email so that I can prepare for the future issue to dive deeper into the details

AC:

- [ ] Figure out whodunit

Support:
@brandocalrissian

**Comment by beebouttw** [comment]
First shot, these are the senior stakeholders for Office 365, broadly in charge of migration:

IRM/OPS/ENM – Gerald Caron

IRM/OPS/SIO – Michelle Sparrow-Walker & Earl Underwood

IRM/OPS/MSO – Karen Finer

IRM/OPS/CCS – Misty Knotts

IRM/BMP/DCIO – Karen Mummaw

IRM/VMO – Corey Ludwig​

IRM/DCIO/IA - Al Bowden & Dan Danckaert

**Comment by beebouttw** [comment]
These are all high-level folks, too high to know the answers to specific questions, but it's a start.

**Comment by karareinsel** [comment]
Since we have the high level names, are we good to close out this issue? I'd like to create a new issue that is specifically for contacting and speaking with these people. @beebouttw are the names above in any kind of priority order? Meaning, are more likely to have success with one person vs another?

**Comment by MeghanLuecke** [comment]
Recommend we also take a look at additional options to get you all into an email inbox here - if we can given clearance limitations. That might help make things feel more real (rather than having to talk about systems and options in the abstract). Discussed with Tyler and happy to help if/when needed!

**Comment by beebouttw** [comment]
In speaking with Eric Johnson from ExecTech, he said there's no prohibition to sending email data as a .pst file.  Broadly, ExecTech owns Ops mailboxes, so we will need to speak to them regarding extraction.  Is it possible to get started on [issue #146](https://app.zenhub.com/workspaces/dos-ops-center-5bcf771b4b5806bc2bee7b27/issues/18f/dos-ops-center/146) to clarify what this issue entails?

**Comment by yowill** [comment]
@tadhg-ohiggins  Is this done now?
