### ISSUE TITLE
Prepare plan and script for Ops team to start conducting audience feedback research

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#175]
As a Ops Content Strategist, I want to start examining and building a plan for collecting audience feedback for content using the research methods recommended from 18F previous to make a plan for defining, implementing, and tracking metrics of our work. 

Background: 
This will be a cultural change so preparing for it and training people to understand regular gathering of feedback will take some time, but is necessary. This will be pitched as a data gathering project for State. Doing this sooner than later, ideal an early test in Sprint Jordan (even if it's just a beta test of 2-3 people, that's great). DOS folks would definitely be able to help run these meetings (and we would probably get more candid feedback as we've seen from previous State-to-State interviews).

Previous research and recommendations: https://docs.google.com/document/u/2/d/1BJYGVbiEAU5J1hmUvMIBFhRAcxb4JpgZcnnVidE2wfw/edit#heading=h.jewrk4jx9fvs

Two research tasks this issue is currently blocking that could provide some information or opportunities #169 #185

AC:
- [x] Ashley would like to have a draft plan / proposal to run by Bob sooner than later (ideally by the end of the first week of the Sprint). Ops to develop a first draft framework to share with 18F for 18F's review, edits, additions, etc.  
- [x] Building on the Ops first draft framework, prepare a draft calendar and cadence plan for Ops folks to start collecting feedback from their audience at regular intervals. Update: Ops will need to review this with Bob NLT OOB Friday 3/22.
- [x] For this first round of audience outreach, select a research method from the 4 previously proposed: User interviews, Card Sorting, Paper Prototypes, Over-the-Shoulder observations, discussing with Ops Content Strategists the benefit, to start audience feedback collection. Update: Ops will need to review this with Bob NLT OOB Friday 3/22 https://docs.google.com/document/u/2/d/1BJYGVbiEAU5J1hmUvMIBFhRAcxb4JpgZcnnVidE2wfw/edit#heading=h.jewrk4jx9fvs
- [x] Help them prepare a script for request for time, scope of what we're asking, what the future cadence of interviews might be, show them the value of what we're doing to them, etc. in order to get subjects feedback
- [x] Assist with any prep for the 2-3 interviews the Ops to test within this Sprint (#169 )

Support:
@MeghanLuecke 
@matt-dobson 
@vishaliyer-18f

**Comment by yowill** [comment]
Use LOI research as the initial test? #169

**Comment by karareinsel** [comment]
Added @MeghanLuecke draft [Audience Outreach Plan.docx](https://github.com/18F/dos-ops-center/files/2983590/Audience.Outreach.Plan.docx)

**Comment by karareinsel** [comment]
I converted Meghan's Word document into a Google doc for easier editing and collaboration and it lives in the Shared Deliverables (Partners) folder https://docs.google.com/document/d/1q2RYextymFuff50a9YjGZAXId9v2or2hCJOFIOXdBis/edit

**Comment by karareinsel** [comment]
@matt-dobson and @durland18F for the 4th AC above (Help them prepare a script for request for time ...) @MeghanLuecke is hoping to reach out to testing participants today - is the outreach script at a point where it can be shared?

**Comment by vishaliyer-18f** [comment]
@karareinsel @MeghanLuecke Here you go- https://docs.google.com/document/d/1q2RYextymFuff50a9YjGZAXId9v2or2hCJOFIOXdBis/edit#bookmark=id.y7dsvu5ezvyn. 

We've estimated 60 minutes for the LOI tests since we're doing both the ranking and diving deeper into what they find useful in each product.

**Comment by karareinsel** [comment]
Calling this out for @matt-dobson @durland18F @brandocalrissian @MeghanLuecke @beebouttw @vishaliyer-18f . These are the LOI questions that we asked in the first round and they need to be asked in this around of testing so that the LOE/LOI data can be updated with the reader feedback.
*Timeliness* (customer urgency)

- Less than a day
- Within several days
- Highly variable - generally one week or more

*Reference value* (has a long shelf life)

- Years
- Less than a year
- Rarely referenced, time-bound content

*Request frequency*

- Regularly
- Intermittently
- Almost never

*Need for absolute accuracy*

- Must be absolutely accurate
- As accurate as possible

*Perception of value to Mahogany*

- High value
- Some value
- No value

*Perception of value to greater State Department*
- High value
- Some value
- No value

**Comment by karareinsel** [comment]
Calling this out for @matt-dobson @durland18F @brandocalrissian @MeghanLuecke @beebouttw @vishaliyer-18f . These are the LOI questions that we asked in the first round and they need to be asked in this around of testing so that the LOE/LOI data can be updated with the reader feedback.
*Timeliness* (customer urgency)

- Less than a day
- Within several days
- Highly variable - generally one week or more

*Reference value* (has a long shelf life)

- Years
- Less than a year
- Rarely referenced, time-bound content

*Request frequency*

- Regularly
- Intermittently
- Almost never

*Need for absolute accuracy*

- Must be absolutely accurate
- As accurate as possible

*Perception of value to Mahogany*

- High value
- Some value
- No value

*Perception of value to greater State Department*
- High value
- Some value
- No value

**Comment by MeghanLuecke** [comment]
Thanks Kara and team - I'm adding this update for our records: 
1. We cannot get 60 minutes with subjects, so we revised down our expectations for how many exercises we can accomplish accordingly. We may have some subjects who agree to an hour, but in general, we will not get in the door unless we keep it to 30 minutes or less. This is a best practice we validated with previous internal Ops exercises and appears true for external customers as well (based on how difficult it has been to get people on the calendar this week!). Please plan for any future tests to be conducted in 30 minutes or less unless this gets invalidated somehow in coming weeks. 
2. Per Kara's note above about the "script for request for time" AC, @durland18F  and @matt-dobson , we are still hoping to receive that from you for future use. This week I've been reaching out to people I know personally in order to expedite the process and ensure we get some data, but in future we will need that script so that other Ops team members can help get involved in user research with customers we don't know personally.

**Comment by matt-dobson** [comment]
@MeghanLuecke The script template for request for time is the last item in this doc: https://docs.google.com/document/d/1q2RYextymFuff50a9YjGZAXId9v2or2hCJOFIOXdBis/edit?usp=sharing

I've adjusted the time to reflect your note about sessions being 30 minutes or less. Can we help with updating this script or anything else to help other Ops team members get involved?

**Comment by MeghanLuecke** [comment]
Thanks! This is helpful to start with and we'll make a couple tweaks for our target audience (for example, I'd like to find a way to concisely explain in laymen's terms what the "activities" are, without using terms like "card sorting" - even though I know you have hyperlinks there, I want the email to be clear to readers without them having to click for references).
