### ISSUE TITLE
Comprehensive source information ingestion prototype

### ISSUE THREAD

**Issue by matt-dobson** [18F/dos-ops-center#186]
As an Ops Officer (CMS or Watch) I need to keep track of and be able to see in one place all of the information/data that is ingested and used to create Ops products. 

So that we provide timely, accurate and complete analysis and news for our audience(s)

Hypothesis
We believe Ops Officers have a problem creating a comprehensive products because it is difficult to gather information efficiently from a disparate set of sources. 

We can help them by creating an interface that consolidates all sources of crisis-related information. 

We'll know we're right if they can assemble products more quickly with fewer gaps in information.

AC 
- [ ] Collect examples from State
- [ ] Synthesize and clarify data audit (#178) [CAN WE FLESH THIS OUT FURTHER? - MHL]
- [ ] Create data ingestion prototype (testing will happen in the next sprint)

**Comment by karareinsel** [comment]
Adding link to #178 it's an audit of the data sources - this will be an important first step to figure out the best way to ingest data.

**Comment by karareinsel** [comment]
Adding notes from @MeghanLuecke about this issue. She described a desired user scenario would be that a dashboard could dynamically read and ingest emails based on meta data (such as country or region) to display on a page about a particular country. So you would be looking at a dashboard page for a region or country, and this page would display all of the relevant emails for that country so that a CMS officer or Watch stander wouldn't have to switch back and forth from email to other programs.

**Comment by yowill** [comment]
Tabled until perhaps after Sprint Liechtenstein?

**Comment by vishaliyer-18f** [comment]
@MeghanLuecke, can you share the paper prototypes created last year on this?

**Comment by MeghanLuecke** [comment]
@vishaliyer-18f  yes, I'll send via email (they should not live on GitHub for now).

**Comment by karareinsel** [comment]
This may become redundant with #230 .

**Comment by karareinsel** [comment]
Closing in favor of #232
