### ISSUE TITLE
Organize a list of vendors to speak to and review their products

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#41]
As an 18F researcher, I want to learn more about the vendors DOS is considering for outside information / visualization of data / breaking news / social media news services, so that I can learn about their capabilities, functionalities, and benefits.

AC:

- [x] Collect the list of vendors from Tyler
- [x] Connect with Holly also about this for her suggestions
- [ ] Review the list and functions
- [ ] Identify who to talk to first

**Comment by beebouttw** [comment]
Current Vendors
•	Dataminr
o	Dataminr is the company behind First Alert, a web-based portal that applies machine learning, AI, and human translation to social media to detect, classify, and determine the significance of public information in real-time. Ops uses First Alert as a news-gathering tool, alerting us sometimes hours before news wires about breaking news around the world.
o	Renewed for FY 2019 in September, Ops has 10 months left of service.  Ops purchased 30 licenses for the "First Alert" product at full price, and is using provisional licenses for the remainder of our staff.  If the Department acquires an enterprise license for Dataminr software during the fiscal year, our paid licenses convert automatically, and we need approximately 20 new volume licenses to ensure every watch officer has one.
•	Infoviewer
o	InfoDesk makes InfoViewer, a tool to read and process news wires provided by AP, Reuters, and AFP.  Ops separately purchases subscriptions to AP and Reuters, but dropped our AFP subscription this year.  Infoviewer displays news wires in a readable format, which Ops currently sends through our distribution portal.
o	Ops is very satisfied with the service InfoDesk provides, and expanded our partnership this year.  Starting soon, Ops will have a single news homepage on the Infoviewer domain (State.Infoviewer.com) for Department news customers to read news, set up subscriptions based on their preferences, and track news items Ops flags for particular attention.
o	Ops is currently in the design process with Infodesk, and expects to have a workable prototype shortly.
 
Prospective Vendors
•	Factal
o	Factal is a company that came out of the ashes of Breakingnews.com, which Ops used heavily before it was shut down in December 2016.  Factal works with Twitter and other social media sources to identify breaking news content, but their specific advantage is an experienced editorial team to vet stories and provide continuity to a series of alerts.  They do not currently have fast human translation of headlines, they rely on machine translation from native language to English, then have a native English-speaking editor refine the translation into a propoer headline.  Furthermore, they have functionality to "chat" with the editor on duty through the software for further clarification on a story.
o	Factal is currently speaking with their legal team to decide whether they can extend their service to a Government client.  Currently, they're in the fifth week of operation, and they only have private sector clients.  Their licenses promise to be significantly cheaper than Dataminr, and they support volume licenses rather than per-seat licenses like Dataminr.
•	Everbridge
o	Everbridge is a global provider of SaaS-based critical communications and enterprise safety solutions. It began operations in 2002. In an emergency, Everbridge sends messages via telephone, text message and email, but stop once they know that a person has read a message.  Additionally, Everbridge recently deployed a desktop dashboard aggregating sensor data and other data into a single screen, potentially making data archiving and visualization significantly easier.
o	Ops spoke to Everbridge at the 2018 IAEM conference, but has not yet received a full demo.  This software is mostly targeted toward CMS and Taskforces, but could be useful as a messaging service to allow the watch floor to send SMS messages.
 
Additional Consideration
•	GeoSpark
o	GeoSpark makes Hyperion software, a notification and analysis tool built by former IC analysts. They claim to "bridge the gaps between data analysis, threat assessment, and reporting." Their service combines multi-variate data from space, social media, news reporting and cyber with machine learning, artificial intelligence and natural language generation to serve as a decision-making aid.  GeoSpark has offered Ops a free demo of their software, but their "threat report" model seems poorly suited to Ops's alerting and briefing philosophy at this time.
•	Dynamis
o	Virginia-based Dynamis makes emergency operations and support software used by large organization to track physical and human assets.  Their largest client is the nation of Belgium, who they met while pitching their software to NATO.  Their COBRA software seems to have CMS potential, especially for its role in emergency management data organization.  From the website:
The COBRA Emergency Management Information System platform provides your emergency management organization the features and capabilities needed to manage every size and type of crisis at the tactical, command, strategic, State, and Federal levels. COBRA is a scalable suite of digital tools to support daily facility operations as well as managing special events, emergencies, and disasters. It provides a distributed collaboration environment including resource tracking, activity logs, chat rooms, interactive maps, and multiple other tools and resources that can be shared by users at the local, regional, and headquarters level. COBRA provides facility managers, safety and security staff, and support staff the capability to post and share information about an incident or event, the associated impacts to the facility, critical infrastructure, and the surrounding environment. This supports management, response, and recovery operations by capturing real-time information on the situation and facilitates seamless information sharing with the appropriate authorities on current activities and the anticipated actions needed to effectively manage the situation.
•	PreData
o	PreData makes a suite of tools that claim to be able to use behavioral indicators (Facebook posts, wikipedia edits, youtube views, etc.) to predict unrest.  Their signature product is a daily report assigning a single threat risk number to a country or region, based on criteria the client sets up with PreData engineers.  While this information could theoretically be useful, there is little indication at this time it actually works without significant man hours dedicated to assembling the criteria and reports, and a single daily number doesn't give Ops any briefable insight.  This does not fit our current alerting and briefing model.

**Comment by yowill** [comment]
Holding off on this to focus on vendors that are currently working with DOS.

**Comment by karareinsel** [comment]
@yowill I think we can close out this issue. We will attend the Everbridge demo on 3/20/2019.

**Comment by yowill** [comment]
Huzzah! Done!
