### ISSUE TITLE
Obtain list of cloud functionality supported in production by IRM's cloud agreement

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#92]
IRM has cloud under contract at the FISMA moderate level; deploying to this cloud covers all but 32 A&A controls. "Cloud" includes lots of different features. IRM has a list of what cloud functionality is covered with regard to IA's A&A controls.  We'd like to review this list.

- [ ] Obtain a copy of the list

**Comment by yowill** [comment]
@beebouttw is shakin' the tree to find this content. He found lots of weird stuff. He'll get it to us.

**Comment by beebouttw** [comment]
Reached back out to Alen Kirkorian, Kenny LaVolpe, and Bill Bonnett (Deputy Director IRM/BSP/SPO) for a copy of any list pertaining to A&A processes not covered by FISMA moderate authorization for AWS or Azure.

**Comment by beebouttw** [comment]
Got what I believe to be an authoritative answer from Gene Cho, the senior in IRM/IA/ITSC/AA

"At the current state, our team is still working on the Azure and AWS common controls that can be inherited by the application owners who use one of these cloud services. AWS has recently gone through system level A&A process and Azure is still awaiting. Although our team is working very diligently to get the common control assessment, I can not guarantee any time frame when it's going to be done. When AWS and Azure get its system level ATO, technically, applications can move to the environments. Whether those applications can inherit common controls before A&A, that is TBD."

I am happy to forward follow-up questions to Gene, since that's far from the "32 controls" list Kenny hinted at.

**Comment by beebouttw** [comment]
I had a fruitful discussion with Gene, who is high up in the office handling A&As.  Here were my takeaways:

1)  AWS and Azure are both currently in the A&A process, awaiting a full ATO.  

2)  Both AWS and Azure contain over 600 items that need to be addressed, and IRM has addressed only about 300 of them.  They are working to address the remainder.

3)  Any solution implemented in either AWS or Azure currently would need to overcome 300+ A&A items for its own individual ATO.  This is a significant hurdle.

4)  Gene could not confirm that either system, AWS or Azure, would be ATO'ed by summer.

5)  Gene says he "wished there were only 32 outstanding controls" while laughing.  Gene feels this is trickier than Kenny LaVolpe let on.
